import { rel } from './templates.mjs';
import { EXTERNAL, ext, sharedReferenceGrid } from './methodology-references.mjs';

export function englishMethodology() {
  return `<article class="methodology-story" aria-label="EGX Alpha methodology">
    <header class="methodology-hero">
      <p class="eyebrow">WHY /ALPHA EXISTS</p>
      <h1>The index tells you how the market moved. /Alpha tells you where to look.</h1>
      <p class="lede">The persistent problem in the Egyptian market is not a shortage of prices, charts or opinions. It is selection. An index compresses many stocks into one benchmark number. Investors, however, make decisions among individual stocks — and the distance between those stocks is where opportunity and loss separate.</p>
      <div class="methodology-question"><span>THE QUESTION /ALPHA ANSWERS</span><strong>Among the eligible EGX stocks the engine can evaluate after a completed session, where does each stock rank relative to the rest for the next 1, 3, 5 and 10 trading days?</strong></div>
    </header>

    <section class="methodology-section"><span class="methodology-index">01 / THE PROBLEM</span><div class="methodology-copy"><h2>The market average is useful. It is also incomplete.</h2><p>EGX indices are built to summarize defined baskets of securities according to published rules. That makes them essential benchmarks; it does not make them stock-selection engines. The investor’s harder problem begins after the benchmark: which names are separating from the rest, and which deserve attention before the next sessions?</p><p>A research process anchored only to average market performance can miss stocks that move materially ahead of that average and remain exposed to stocks that fall behind it. EGX /Alpha was conceived around this gap. It does not ask whether one stock looks attractive in isolation. It ranks the eligible opportunity set against itself.</p><p>That distinction is the foundation of the system. The public question is relative by design: <strong>where does each stock stand among the alternatives?</strong> The official ${ext(EXTERNAL.egx, 'Egyptian Exchange index methodology')} provides the benchmark context; /Alpha addresses a different decision layer — cross-sectional priority.</p></div></section>

    <section class="methodology-section"><span class="methodology-index">02 / THE DAILY SIGNAL</span><div class="methodology-copy"><h2>From market noise to an order of priority.</h2><p>After every completed EGX session, /Alpha scores the eligible stocks it can evaluate and publishes a complete ranking for four forward horizons. A higher position means a stronger model preference relative to the other eligible stocks at that same horizon. It does <strong>not</strong> mean a guaranteed gain, and it does not require the stock to deliver a positive absolute return.</p><p><strong>Relative Rank</strong> answers where the stock stands. <strong>Model Direction</strong> adds a separate Positive, Neutral or Negative classification of its forward market-relative view. Read together, they turn a broad market into a practical research sequence: what deserves attention first, what deserves context, and what can wait.</p><div class="horizon-line"><span>1D</span><span>3D</span><span>5D</span><span>10D</span></div><div class="priority-grid"><article class="priority-card"><span>01</span><strong>Rank the alternatives</strong><p>Every eligible stock receives a place in the selected horizon’s order.</p></article><article class="priority-card"><span>02</span><strong>Read direction separately</strong><p>Direction adds context without pretending that rank is a probability or a price target.</p></article><article class="priority-card"><span>03</span><strong>Research in order</strong><p>The output is a disciplined attention map, not an instruction to trade.</p></article></div><div class="methodology-actions"><a href="${rel('/today/')}">OPEN TODAY’S RANKING</a><a href="${rel('/investor-guide/')}">READ THE INVESTOR GUIDE</a><a href="${rel('/archive/')}">EXPLORE MODEL MEMORY</a></div></div></section>

    <section class="methodology-section"><span class="methodology-index">03 / DEEP LEARNING</span><div class="methodology-copy"><h2>Why deep learning? Because markets are interactions, not checklists.</h2><p>Market behaviour changes through combinations of price action, trading activity, volatility, liquidity, sector behaviour and the wider market state. Those relationships can be nonlinear and can change through time. EGX /Alpha uses deep learning to represent that complexity and produce one consistent cross-sectional ranking problem rather than reduce every decision to a single rule.</p><p>This choice is grounded in modern empirical finance. ${ext(EXTERNAL.gu, 'Gu, Kelly and Xiu')} document the value of machine-learning methods — including neural networks — when predictive information interacts nonlinearly. ${ext(EXTERNAL.chen, 'Chen, Pelger and Zhu')} show how deep neural networks can model broad conditioning information and time variation in individual-stock asset pricing. Those papers do not describe /Alpha’s proprietary model; they establish the research context for using deep learning on high-dimensional, time-varying financial data.</p><p>/Alpha learns from earlier market history, is evaluated on later unseen periods, and runs a reviewed production model when it publishes the daily ranking. The live model does not rewrite itself while it is making that day’s public call.</p><aside class="methodology-note">The public methodology explains the research claim and the governance around it. Exact architecture, feature construction, training settings, internal numerical scores, model files and implementation paths remain private.</aside></div></section>

    <section class="methodology-section"><span class="methodology-index">04 / PROGRESSIVE LEARNING</span><div class="methodology-copy"><h2>Every forecast becomes future evidence. Every new generation must earn promotion.</h2><p>EGX /Alpha does not blindly retrain itself every night. It uses a stricter loop. A forecast is issued first. Time passes. Only when the relevant trading horizon has matured can the realised outcome be scored. Those matured outcomes accumulate into model evidence; source quality and drift are monitored; the live model’s trust state can be reassessed.</p><p>When enough evidence exists and deterioration warrants research, the system can create a bounded challenger candidate from realised forecast history. A challenger is not the live model. It remains outside production until it has been evaluated and a human-governed promotion decision is made.</p><div class="learning-loop"><span class="learning-step">OBSERVE</span><i class="learning-arrow">→</i><span class="learning-step">RANK</span><i class="learning-arrow">→</i><span class="learning-step">WAIT</span><i class="learning-arrow">→</i><span class="learning-step">SCORE</span><i class="learning-arrow">→</i><span class="learning-step">LEARN</span><i class="learning-arrow">→</i><span class="learning-step">CHALLENGE</span><i class="learning-arrow">→</i><span class="learning-step">REVIEW</span></div><p>This is progressive, generational learning: the system turns old forecasts into new evidence without allowing a few good or bad days to rewrite the production model. The objective is not constant change. The objective is controlled improvement.</p></div></section>

    <section class="methodology-section"><span class="methodology-index">05 / BEYOND THE WEBSITE</span><div class="methodology-copy"><h2>The public website is the research surface, not the engine room.</h2><p>What you see publicly is intentionally narrow: the daily ranking, Model Direction, rank movement, four horizons, preserved model history, evidence disclosures and a machine-readable public record. That is enough to understand what the model is saying and to verify what was published.</p><p>The research system behind that surface is broader. It maintains persistent market memory, validates observations, stores forecasts, scores matured outcomes, monitors source quality and drift, maintains trust and evidence state, and supports governed challenger research. Those capabilities exist to make the public signal more disciplined — not to turn the website into a technical dump.</p><div class="public-private"><article><span>PUBLIC SURFACE</span><h3>What an investor needs to use and verify /Alpha.</h3><p>Rank · Model Direction · Rank Move · 1D / 3D / 5D / 10D · archive · evidence · public JSON.</p></article><article><span>PRIVATE RESEARCH SYSTEM</span><h3>What keeps the signal governed over time.</h3><p>Persistent memory · observation quality · realised scoring · drift and trust monitoring · challenger research · audit history.</p></article></div><div class="methodology-actions"><a href="${rel('/data/latest.json')}">VERIFY PUBLIC RECORD</a><a href="${rel('/institutional/')}">INSTITUTIONAL RESEARCH</a></div></div></section>

    <section class="methodology-section"><span class="methodology-index">06 / RESEARCH AGENDA</span><div class="methodology-copy"><h2>More depth. More evidence. No novelty for its own sake.</h2><p>The future research agenda is aimed at making the ranking more robust and more useful without weakening the discipline that makes it credible. New capabilities must improve the decision problem /Alpha was built to solve: identifying relative opportunity across the Egyptian market.</p><div class="agenda-grid"><article class="agenda-card"><span>01</span><strong>Regime resilience</strong><p>Study how model generations remain useful as market conditions and relationships change.</p></article><article class="agenda-card"><span>02</span><strong>Evidence depth</strong><p>Expand matured live-outcome evidence, calibration and long-run model accountability.</p></article><article class="agenda-card"><span>03</span><strong>Cross-horizon intelligence</strong><p>Study when agreement or disagreement across 1D, 3D, 5D and 10D carries useful research information.</p></article><article class="agenda-card"><span>04</span><strong>Market structure</strong><p>Deepen how the research system represents changing relationships across the EGX universe.</p></article><article class="agenda-card"><span>05</span><strong>Governed model generations</strong><p>Develop challengers under the same evidence-first, human-reviewed promotion discipline.</p></article><article class="agenda-card"><span>06</span><strong>Institutional research surfaces</strong><p>Extend controlled research distribution without exposing the proprietary model core.</p></article></div></div></section>

    <section class="reference-block"><h2>References and verification.</h2><p>External references provide the academic and market context for the ideas above; they are not descriptions of EGX /Alpha’s proprietary implementation. Internal references let any visitor verify the public output and its chronology.</p>${sharedReferenceGrid(false)}</section>
    <aside class="methodology-closing"><strong>An index gives you the average. /Alpha gives you the order.</strong><p>EGX /Alpha does not decide what you should buy. It makes the first research decision faster and more disciplined: where should serious attention begin before the next trading sessions?</p></aside>
  </article>`;
}
