import { escapeHtml, siteFooter, siteHeader } from './templates.mjs';

const METHODOLOGY_CSS = String.raw`
.page-methodology .white-paper{width:min(100%,1160px);margin:34px auto 0;border:1px solid var(--line);border-radius:14px;background:var(--surface);overflow:hidden}
.page-methodology .paper-cover{padding:clamp(34px,6vw,74px);border-bottom:1px solid var(--line);background:linear-gradient(180deg,color-mix(in srgb,var(--blue) 5%,var(--surface)),var(--surface))}
.page-methodology .paper-cover h1{max-width:15ch;margin:12px 0 20px;font-size:clamp(2.7rem,6vw,5.4rem)}
.page-methodology .paper-cover .abstract{max-width:82ch;margin:0;color:var(--soft);font-size:clamp(1rem,1.35vw,1.18rem);line-height:1.72}
.page-methodology .paper-meta{display:grid;grid-template-columns:repeat(4,1fr);margin-top:34px;border:1px solid var(--line);border-radius:10px;overflow:hidden;background:var(--line);gap:1px}
.page-methodology .paper-meta div{padding:15px 16px;background:var(--surface-2)}
.page-methodology .paper-meta span{display:block;color:var(--muted);font-family:var(--mono);font-size:.58rem;letter-spacing:.07em}
.page-methodology .paper-meta strong{display:block;margin-top:6px;color:var(--text);font-family:var(--mono);font-size:.75rem}
.page-methodology .paper-section{padding:clamp(30px,5vw,58px) clamp(24px,6vw,72px);border-bottom:1px solid var(--line)}
.page-methodology .paper-section:last-of-type{border-bottom:0}
.page-methodology .section-head{display:grid;grid-template-columns:64px minmax(0,1fr);gap:20px;align-items:start;margin-bottom:24px}
.page-methodology .section-index{color:var(--blue);font-family:var(--mono);font-size:.72rem;padding-top:7px}
.page-methodology .section-head h2{max-width:22ch;margin:0;font-size:clamp(1.65rem,3vw,2.55rem)}
.page-methodology .section-copy{max-width:84ch;margin-left:84px}
.page-methodology .section-copy p{color:var(--soft);font-size:.96rem;line-height:1.72}
.page-methodology .section-copy p:last-child{margin-bottom:0}
.page-methodology .sim-flow{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px;margin:30px 0 0}
.page-methodology .sim-node{position:relative;min-height:124px;padding:16px;border:1px solid var(--line);border-radius:10px;background:var(--surface-2)}
.page-methodology .sim-node:not(:last-child)::after{content:'→';position:absolute;right:-9px;top:50%;z-index:2;transform:translateY(-50%);color:var(--blue);font-family:var(--mono);font-weight:900}
.page-methodology .sim-node span{display:block;color:var(--blue);font-family:var(--mono);font-size:.55rem;letter-spacing:.08em}
.page-methodology .sim-node strong{display:block;margin-top:10px;font-size:.86rem;line-height:1.25}
.page-methodology .sim-node p{margin:7px 0 0;color:var(--muted);font-size:.7rem;line-height:1.45}
.page-methodology .horizon-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:28px}
.page-methodology .horizon-card{padding:20px;border:1px solid var(--line);border-radius:11px;background:var(--surface-2)}
.page-methodology .horizon-card b{display:block;color:var(--blue);font-family:var(--mono);font-size:1.5rem}
.page-methodology .horizon-card strong{display:block;margin-top:7px;font-size:.88rem}
.page-methodology .horizon-card p{margin:7px 0 0;color:var(--muted);font-size:.74rem;line-height:1.5}
.page-methodology .math-card{display:grid;grid-template-columns:minmax(210px,.8fr) 1.2fr;gap:20px;margin-top:28px;padding:22px;border:1px solid var(--line);border-radius:11px;background:var(--surface-2)}
.page-methodology .formula{display:grid;place-items:center;min-height:126px;border:1px solid var(--line);border-radius:9px;background:var(--surface);color:var(--text);font-family:var(--mono);font-size:clamp(.86rem,2vw,1.15rem);text-align:center}
.page-methodology .math-card p{margin:0;color:var(--soft);font-size:.86rem;line-height:1.65}
.page-methodology .signal-geometry{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:28px}
.page-methodology .signal-case{padding:20px;border:1px solid var(--line);border-radius:11px;background:var(--surface-2)}
.page-methodology .signal-case span{font-family:var(--mono);font-size:.58rem;letter-spacing:.06em}
.page-methodology .signal-case strong{display:block;margin:8px 0 6px}
.page-methodology .signal-case p{margin:0;color:var(--muted);font-size:.77rem;line-height:1.5}
.page-methodology .tone-positive-case{border-top:3px solid var(--positive)}
.page-methodology .tone-neutral-case{border-top:3px solid var(--neutral)}
.page-methodology .tone-negative-case{border-top:3px solid var(--negative)}
.page-methodology .validation-lane{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:28px}
.page-methodology .validation-step{padding:18px;border:1px solid var(--line);border-radius:10px;background:var(--surface-2)}
.page-methodology .validation-step span{color:var(--blue);font-family:var(--mono);font-size:.56rem}
.page-methodology .validation-step strong{display:block;margin-top:8px;font-size:.82rem}
.page-methodology .validation-step p{margin:6px 0 0;color:var(--muted);font-size:.71rem;line-height:1.48}
.page-methodology .integrity-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:28px}
.page-methodology .integrity-card{display:grid;grid-template-columns:34px 1fr;gap:12px;padding:17px;border:1px solid var(--line);border-radius:10px;background:var(--surface-2)}
.page-methodology .integrity-card span{color:var(--blue);font-family:var(--mono);font-size:.68rem}
.page-methodology .integrity-card strong{display:block;font-size:.86rem}
.page-methodology .integrity-card p{margin:5px 0 0;color:var(--muted);font-size:.75rem;line-height:1.5}
.page-methodology .evidence-loop{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:12px;align-items:center;margin-top:28px;padding:22px;border:1px solid var(--line);border-radius:11px;background:var(--surface-2)}
.page-methodology .evidence-loop article{padding:18px;border:1px solid var(--line);border-radius:9px;background:var(--surface)}
.page-methodology .evidence-loop article span{display:block;color:var(--blue);font-family:var(--mono);font-size:.55rem}
.page-methodology .evidence-loop article strong{display:block;margin-top:8px;font-size:.84rem}
.page-methodology .evidence-loop article p{margin:6px 0 0;color:var(--muted);font-size:.72rem;line-height:1.48}
.page-methodology .evidence-loop>i{color:var(--blue);font-family:var(--mono);font-style:normal;font-weight:900}
.page-methodology .boundary-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:28px}
.page-methodology .boundary-card{padding:22px;border:1px solid var(--line);border-radius:11px;background:var(--surface-2)}
.page-methodology .boundary-card strong{display:block;font-size:.9rem}
.page-methodology .boundary-card ul{margin:12px 0 0;padding-left:18px;color:var(--muted);font-size:.78rem;line-height:1.65}
.page-methodology .paper-note{margin-top:24px;padding:16px 18px;border-left:3px solid var(--blue);background:var(--surface-2);color:var(--muted);font-size:.82rem;line-height:1.6}
.page-methodology .paper-closing{padding:34px clamp(24px,6vw,72px);background:var(--surface-2)}
.page-methodology .paper-closing p{max-width:86ch;margin:0;color:var(--soft);font-size:.9rem;line-height:1.7}
@media(max-width:980px){.page-methodology .sim-flow{grid-template-columns:repeat(3,1fr)}.page-methodology .sim-node:nth-child(3)::after{display:none}.page-methodology .validation-lane{grid-template-columns:repeat(3,1fr)}.page-methodology .horizon-grid{grid-template-columns:1fr 1fr}}
@media(max-width:700px){.page-methodology .paper-cover h1{max-width:none;font-size:clamp(2.35rem,11vw,3.45rem)}.page-methodology .paper-meta{grid-template-columns:1fr 1fr}.page-methodology .section-head{grid-template-columns:1fr;gap:6px}.page-methodology .section-copy{margin-left:0}.page-methodology .sim-flow,.page-methodology .validation-lane,.page-methodology .signal-geometry,.page-methodology .integrity-grid,.page-methodology .boundary-grid{grid-template-columns:1fr}.page-methodology .sim-node::after{display:none!important}.page-methodology .math-card{grid-template-columns:1fr}.page-methodology .evidence-loop{grid-template-columns:1fr}.page-methodology .evidence-loop>i{transform:rotate(90deg);text-align:center}.page-methodology .horizon-grid{grid-template-columns:1fr 1fr}}
@media(max-width:430px){.page-methodology .paper-meta,.page-methodology .horizon-grid{grid-template-columns:1fr}.page-methodology .paper-section{padding-left:18px;padding-right:18px}.page-methodology .paper-cover{padding-left:18px;padding-right:18px}}
@media print{@page{size:A4;margin:14mm}.page-methodology .topbar,.page-methodology .site-footer{display:none!important}.page-methodology .site-shell{width:100%;padding:0}.page-methodology .white-paper{margin:0;border:0}.page-methodology .paper-section,.page-methodology .sim-flow,.page-methodology .validation-lane,.page-methodology .boundary-grid{break-inside:avoid}}
`;

function meta(label,value){return `<div><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`;}
function simNode(n,title,body){return `<article class="sim-node"><span>${escapeHtml(n)}</span><strong>${escapeHtml(title)}</strong><p>${escapeHtml(body)}</p></article>`;}
function horizon(label,title,body){return `<article class="horizon-card"><b>${escapeHtml(label)}</b><strong>${escapeHtml(title)}</strong><p>${escapeHtml(body)}</p></article>`;}
function validation(n,title,body){return `<article class="validation-step"><span>${escapeHtml(n)}</span><strong>${escapeHtml(title)}</strong><p>${escapeHtml(body)}</p></article>`;}
function integrity(n,title,body){return `<article class="integrity-card"><span>${escapeHtml(n)}</span><div><strong>${escapeHtml(title)}</strong><p>${escapeHtml(body)}</p></div></article>`;}

export function methodologyPage() {
  return `<style id="methodology-document-styles">${METHODOLOGY_CSS}</style><main class="site-shell page-methodology" data-page="methodology">${siteHeader('RESEARCH', 'research')}<article class="white-paper"><header class="paper-cover"><p class="eyebrow">PUBLIC QUANTITATIVE WHITE PAPER</p><h1>EGX /Alpha: time-locked deep-learning ranking for Egyptian equities.</h1><p class="abstract">EGX /Alpha is designed as a repeated market-simulation experiment: at each completed EGX session, the system freezes the information state that was actually knowable, applies a reviewed deep-learning inference package, and ranks the eligible domestic universe across four native forward horizons. The public product exposes the ranking, direction and evidence needed to interpret the model while keeping proprietary model mechanics private.</p><div class="paper-meta">${meta('MARKET','EGYPTIAN EXCHANGE')}${meta('NATIVE HORIZONS','1D / 3D / 5D / 10D')}${meta('RESEARCH DEFAULT','5D FULL RANKING')}${meta('DEFAULT VIEW','5D PRIMARY RESEARCH')}</div></header>

<section class="paper-section"><header class="section-head"><span class="section-index">01</span><h2>The simulation starts with chronology, not statistics.</h2></header><div class="section-copy"><p>A stock-market simulation is credible only when every decision is made from the information state that existed at that moment. /Alpha therefore treats each EGX close as a sealed research state. Data availability, freshness and eligibility are resolved before inference; future observations are not allowed to leak backward into the decision frame.</p><p>The daily run is not an exercise in reconstructing what would have looked attractive with hindsight. It is a forward experiment repeated under the same operational discipline: observe the completed session, lock the state, infer, rank, publish, and only later score outcomes after the relevant horizon has matured.</p></div><div class="sim-flow">${simNode('01','Completed market state','Use post-close observations available for that session.')}${simNode('02','Availability lock','Reject stale, invalid or ineligible observations.')}${simNode('03','Deep inference','Apply the fixed reviewed production model package.')}${simNode('04','Cross-sectional rank','Order the eligible domestic universe from 1 through N.')}${simNode('05','Public projection','Publish only sanitized rank, direction and evidence.')}${simNode('06','Outcome maturity','Score realised evidence only after the horizon exists.')}</div><aside class="paper-note">This time ordering is the core anti-lookahead discipline. A model can be statistically sophisticated and still be useless if its simulation permits information that would not have existed at the decision time.</aside></section>

<section class="paper-section"><header class="section-head"><span class="section-index">02</span><h2>Four horizons are native model questions, not interpolated labels.</h2></header><div class="section-copy"><p>The engine evaluates the eligible universe over four distinct forward trading-day windows. Each horizon produces its own complete cross-sectional ordering of the same eligible symbols for that run. The public interface labels these windows 1D, 3D, 5D and 10D, where D means trading days rather than calendar days.</p><p>The public interface uses one horizon controller across the research terminal. All four native horizons remain one tap away, while 5D is the canonical primary research view and the default state for the full public ranking.</p></div><div class="horizon-grid">${horizon('1D','Next-session view','The shortest forward window for the next trading session.')}${horizon('3D','Short persistence view','Shows whether the relative model view extends beyond one session.')}${horizon('5D','Primary research view','The default public ranking horizon used for deeper comparison.')}${horizon('10D','Extended view','A longer forward window for cross-horizon context.')}</div></section>

<section class="paper-section"><header class="section-head"><span class="section-index">03</span><h2>Rank and direction are deliberately separate signals.</h2></header><div class="section-copy"><p>The engine answers two different questions. Rank asks where a stock sits relative to the rest of the eligible market at the selected horizon. Direction assigns a separate Positive, Neutral or Negative model view. They should be read together rather than collapsed into a single marketing score.</p><p>A high rank with Positive direction is internally aligned. A high rank with Neutral or Negative direction is not a contradiction: the stock can be relatively stronger than peers while the absolute directional view remains weak. That distinction is especially important in broad risk-off or risk-on conditions.</p></div><div class="math-card"><div class="formula">Percentile = 100 × (N − rank + 1) / N</div><p>Rank percentile is a public normalization of the cross-sectional position. It allows an investor to compare a rank across sessions when the eligible universe changes slightly. It is not a probability, confidence score, expected return or hidden model magnitude. Rank Move only shows movement versus the previous completed run at the same horizon.</p></div><div class="signal-geometry"><article class="signal-case tone-positive-case"><span>HIGH RANK + POSITIVE</span><strong>Aligned relative and directional view</strong><p>Use as a stronger research-priority signal, not as a guaranteed gain.</p></article><article class="signal-case tone-neutral-case"><span>HIGH RANK + NEUTRAL</span><strong>Strong relative position, mixed direction</strong><p>The stock ranks well against peers while the directional view remains inconclusive.</p></article><article class="signal-case tone-negative-case"><span>HIGH RANK + NEGATIVE</span><strong>Relative strength inside a weak view</strong><p>A top relative rank does not automatically become a bullish call.</p></article></div></section>

<section class="paper-section"><header class="section-head"><span class="section-index">04</span><h2>The deep-learning layer is fixed during live inference.</h2></header><div class="section-copy"><p>Production inference uses a reviewed neural model package that has already passed development and promotion controls. The live network does not retrain itself while producing the daily public ranking, and the production run does not loosen data-quality rules to force an answer.</p><p>The public white paper intentionally stops at the system level. Exact feature construction, network dimensions, optimization choices, private numerical model outputs and implementation paths remain proprietary. What matters publicly is the reproducible decision protocol around the model: fixed package, time-locked inputs, complete horizon rankings and controlled disclosure.</p></div><div class="integrity-grid">${integrity('A','Fixed production package','Daily inference uses the reviewed live package rather than an online self-modifying model.')}${integrity('B','Same-run universe parity','Native horizons are published over the same eligible symbol set for that completed run.')}${integrity('C','Fail-closed publication','Incomplete or unsafe public records are rejected rather than partially exposed.')}${integrity('D','No invented confidence','The public product never manufactures probability or return precision from rank alone.')}</div></section>

<section class="paper-section"><header class="section-head"><span class="section-index">05</span><h2>Validation is chronological and evidence is separated by stage.</h2></header><div class="section-copy"><p>Development evidence and live realised evidence answer different questions and are therefore kept separate. Model development uses date-ordered partitions and held-out evaluation to test whether ranking behaviour generalises beyond the fitting interval. Production then accumulates a second evidence stream from predictions that were genuinely issued before their outcomes were known.</p><p>This separation prevents a common simulation error: presenting in-sample or reconstructed history as if it were live operational evidence. Historical validation describes the reviewed package; live evidence describes what has actually matured since deployment.</p></div><div class="validation-lane">${validation('01','Training interval','Learn from earlier chronological market history.')}${validation('02','Validation interval','Tune and compare without touching the held-out test interval.')}${validation('03','Held-out test','Evaluate ranking behaviour on unseen later dates.')}${validation('04','Fixed live package','Promote only through controlled human review.')}${validation('05','Live evidence','Score only forecasts whose future horizon has matured.')}</div></section>

<section class="paper-section"><header class="section-head"><span class="section-index">06</span><h2>Realised outcomes arrive after the forecast, never before it.</h2></header><div class="section-copy"><p>Once enough future trading sessions exist, the private evidence loop pairs the earlier forecast state with the realised market outcome. Immature horizons remain pending. Missing or invalid observations do not receive fabricated scores. Aggregate live ranking metrics remain maturity-gated in the public product until the evidence policy allows them to be shown.</p><p>The model is not automatically retrained or promoted because a few recent outcomes look strong or weak. Evidence can trigger review, but model replacement remains a human-governed decision.</p></div><div class="evidence-loop"><article><span>FORECAST TIME</span><strong>Rank the market</strong><p>Issue the forward model record from the sealed session state.</p></article><i>→</i><article><span>WAIT</span><strong>Let the horizon mature</strong><p>No scoring until the required future trading sessions exist.</p></article><i>→</i><article><span>EVIDENCE TIME</span><strong>Measure realised behaviour</strong><p>Accumulate outcome evidence without rewriting the original forecast.</p></article></div></section>

<section class="paper-section"><header class="section-head"><span class="section-index">07</span><h2>The public product is a disclosure layer, not the model core.</h2></header><div class="section-copy"><p>EGX Research publishes enough structure for an investor to inspect the system without publishing the proprietary machinery that makes the ranking economically valuable. Each public session is preserved by date, so visitors can inspect what the system actually disclosed rather than a later rewritten narrative.</p></div><div class="boundary-grid"><article class="boundary-card"><strong>Public research surface</strong><ul><li>Completed analysis date and eligible-universe context</li><li>1D / 3D / 5D / 10D full-universe rankings</li><li>Rank percentile and same-horizon Rank Move</li><li>Positive / Neutral / Negative direction</li><li>Historical held-out evidence and maturity-gated live evidence</li><li>Archive provenance and research-use disclaimer</li></ul></article><article class="boundary-card"><strong>Private research implementation</strong><ul><li>Raw source records and exact feature construction</li><li>Network dimensions, trained parameters and optimization details</li><li>Private numerical forecast magnitudes and model internals</li><li>Internal diagnostics, operational paths and governance state</li><li>Any implementation detail that would expose the proprietary model core</li></ul></article></div></section>

<section class="paper-closing"><p><strong>Interpretation discipline.</strong> EGX /Alpha is a quantitative research system operating under changing market regimes, liquidity conditions and source availability. Its rankings are conditional on the information set, eligible universe and selected horizon at the analysis cutoff. They are not personalised advice, target prices or execution instructions. The intended use is to prioritise research, compare relative model views and inspect a preserved record of forward-looking model output.</p></section></article>${siteFooter()}</main>`;
}
