import { rel } from './templates.mjs';
import { EXTERNAL, ext, sharedReferenceGrid } from './methodology-references.mjs';

export function arabicMethodology() {
  return `<article class="methodology-story" aria-label="منهجية EGX Alpha">
    <header class="methodology-hero">
      <p class="eyebrow">ورقة بحثية كمية عامة · لماذا وُجد EGX /Alpha</p>
      <h1>المؤشر يخبرك كيف تحرك السوق. EGX /Alpha يخبرك أين تبدأ البحث داخله.</h1>
      <p class="lede">المشكلة الأكثر إلحاحاً في البورصة المصرية ليست نقص الأسعار أو الرسوم أو الآراء، بل صعوبة الاختيار. المؤشر يختصر حركة مجموعة من الأسهم في رقم مرجعي واحد، بينما قرار المستثمر يقع في النهاية بين أسهم منفردة — والفارق بين هذه الاختيارات هو المكان الذي تنفصل فيه الفرصة عن الخسارة.</p>
      <div class="methodology-question"><span>السؤال الذي يجيب عنه EGX /Alpha</span><strong>من بين أسهم EGX المؤهلة التي يستطيع المحرك تقييمها بعد اكتمال الجلسة، أين يقف كل سهم مقارنة بالبقية خلال 1 و3 و5 و10 أيام تداول مقبلة؟</strong></div>
    </header>

    <section class="methodology-section"><span class="methodology-index">01 / المشكلة</span><div class="methodology-copy"><h2>متوسط السوق مهم. لكنه لا يكفي لاتخاذ قرار بين الأسهم.</h2><p>مؤشرات EGX صُممت لتلخيص أداء سلال محددة من الأوراق المالية وفق قواعد معلنة. وهذا يجعلها مرجعاً أساسياً لقياس السوق، لكنه لا يجعلها أداة لاختيار الأسهم. السؤال الأصعب يبدأ بعد المؤشر: أي الأسهم تتقدم على غيرها، وأيها يستحق أن يبدأ منه البحث قبل الجلسات التالية؟</p><p>عندما يبقى منهج البحث أسيراً لمتوسط السوق، يمكن أن يفوّت الأسهم التي تبتعد عنه إيجابياً وأن يظل معرضاً للأسهم التي تتراجع خلفه. من هنا وُلد EGX /Alpha. فهو لا يسأل إن كان سهم واحد يبدو جيداً بمعزل عن البقية؛ بل يرتب مجموعة الفرص المؤهلة داخل السوق بعضها مقابل بعض.</p><p>هذه هي الفكرة المؤسسة للمحرك: <strong>أين يقف كل سهم بين البدائل المتاحة؟</strong> وتوضح ${ext(EXTERNAL.egx, 'منهجية المؤشرات الرسمية للبورصة المصرية')} وظيفة المؤشر كمرجع للسوق، بينما يعمل /Alpha في طبقة قرار مختلفة: ترتيب الأولوية بين الأسهم.</p></div></section>

    <section class="methodology-section"><span class="methodology-index">02 / الإشارة اليومية</span><div class="methodology-copy"><h2>من ضوضاء السوق إلى ترتيب واضح للأولوية.</h2><p>بعد كل جلسة مكتملة في البورصة المصرية، يمنح /Alpha كل سهم مؤهل يستطيع تقييمه درجة نموذجية ثم ينشر ترتيباً كاملاً عبر الآفاق الأربعة المستقبلية. كلما ارتفع مركز السهم، كان تفضيل النموذج النسبي له أقوى مقارنة ببقية الأسهم المؤهلة في الأفق نفسه. هذا <strong>لا</strong> يعني ربحاً مضموناً، ولا يشترط أن يحقق السهم عائداً مطلقاً موجباً.</p><p><strong>الترتيب النسبي</strong> يجيب عن موقع السهم بين البدائل. أما <strong>اتجاه النموذج</strong> فيضيف تصنيفاً منفصلاً: إيجابي أو محايد أو سلبي للرؤية المستقبلية النسبية إلى السوق. الترتيب والاتجاه إشارتان منفصلتان، وعند قراءتهما معاً يتحول السوق الواسع إلى تسلسل بحث عملي: ماذا يستحق الانتباه أولاً، وماذا يحتاج إلى سياق أكبر، وماذا يمكن تأجيله.</p><div class="horizon-line"><span>1D</span><span>3D</span><span>5D</span><span>10D</span></div><div class="priority-grid"><article class="priority-card"><span>01</span><strong>رتّب البدائل</strong><p>كل سهم مؤهل يحصل على موقع واضح داخل ترتيب الأفق المحدد.</p></article><article class="priority-card"><span>02</span><strong>اقرأ الاتجاه منفصلاً</strong><p>اتجاه النموذج يضيف سياقاً دون تحويل الترتيب إلى احتمال أو سعر مستهدف.</p></article><article class="priority-card"><span>03</span><strong>ابدأ البحث بالترتيب</strong><p>المخرج خريطة للانتباه البحثي، وليس أمراً بالتداول.</p></article></div><div class="methodology-actions"><a href="${rel('/today/')}">افتح ترتيب اليوم</a><a href="${rel('/investor-guide/')}" >اقرأ دليل المستثمر</a><a href="${rel('/archive/')}">استعرض ذاكرة النموذج</a></div></div></section>

    <section class="methodology-section"><span class="methodology-index">03 / التعلم العميق</span><div class="methodology-copy"><h2>لماذا التعلم العميق؟ لأن السوق علاقات متغيرة، لا قائمة شروط ثابتة.</h2><p>سلوك السوق يتشكل من تفاعل حركة السعر ونشاط التداول والتذبذب والسيولة والقطاع وحالة السوق الأوسع. هذه العلاقات ليست خطية دائماً، كما أنها تتغير بمرور الوقت. تستخدم طبقة التعلم العميق في EGX /Alpha هذا النهج لتمثيل التعقيد وتحويله إلى مسألة ترتيب واحدة ومتسقة، بدلاً من اختزال القرار في قاعدة منفردة.</p><p>هذا الاختيار له أساس واضح في أبحاث التمويل الحديثة. يوضح بحث ${ext(EXTERNAL.gu, 'Gu وKelly وXiu')} قيمة أساليب التعلم الآلي — ومنها الشبكات العصبية — عندما تتفاعل المعلومات التنبؤية بصورة غير خطية. ويبين بحث ${ext(EXTERNAL.chen, 'Chen وPelger وZhu')} كيف تستخدم الشبكات العميقة معلومات واسعة ومتغيرة زمنياً في نماذج تسعير الأسهم. هذه الأبحاث لا تصف نموذج /Alpha الخاص؛ لكنها تشرح السياق العلمي الذي يجعل التعلم العميق مناسباً لبيانات مالية عالية الأبعاد ومتغيرة مع الزمن.</p><p>يتعلم /Alpha من تاريخ سوق أسبق، ويُقيّم على فترات زمنية لاحقة لم تدخل في الملاءمة. التحقق زمني بطبيعته، ثم يستخدم نموذج إنتاج خضع للمراجعة عند إصدار الترتيب اليومي. النموذج الحي لا يعيد كتابة نفسه أثناء إصدار إشارة ذلك اليوم.</p><aside class="methodology-note">تشرح المنهجية العامة الادعاء البحثي والحوكمة التي تحيط به. أما بنية النموذج الدقيقة، وبناء الخصائص، وإعدادات التدريب، والقيم الرقمية الداخلية، وملفات النموذج، ومسارات التنفيذ فتبقى خاصة.</aside></div></section>

    <section class="methodology-section"><span class="methodology-index">04 / التعلم التقدمي</span><div class="methodology-copy"><h2>كل توقع يتحول لاحقاً إلى دليل. وكل جيل جديد يجب أن يستحق مكانه.</h2><p>لا يعيد EGX /Alpha تدريب نفسه بلا ضوابط كل ليلة. التسلسل الزمني هو الحاكم، ويعمل النظام بدورة أكثر صرامة: يصدر التوقع أولاً، ثم يمر الزمن، ولا يُقيّم الناتج إلا بعد نضج الأفق المطلوب. تتراكم النتائج الناضجة كأدلة على أداء النموذج، وتُراقب جودة المصدر والانحرافات، ويمكن إعادة تقييم حالة الثقة في النموذج الحي.</p><p>عندما تتوافر أدلة كافية ويبرر التدهور بحث بديل، يستطيع النظام إنشاء نموذج متحدٍ محدود من سجل النتائج الفعلية للتوقعات. هذا المتحدي لا يصبح نموذج الإنتاج. يظل خارج التشغيل الحي حتى يخضع للتقييم ثم لقرار ترقية تحكمه المراجعة البشرية.</p><div class="learning-loop"><span class="learning-step">رصد</span><i class="learning-arrow">←</i><span class="learning-step">ترتيب</span><i class="learning-arrow">←</i><span class="learning-step">انتظار</span><i class="learning-arrow">←</i><span class="learning-step">تقييم</span><i class="learning-arrow">←</i><span class="learning-step">تعلم</span><i class="learning-arrow">←</i><span class="learning-step">تحدٍ</span><i class="learning-arrow">←</i><span class="learning-step">مراجعة</span></div><p>هذا تعلم تقدمي عبر أجيال محكومة بالأدلة: يحول النظام توقعات الأمس إلى مادة لتقييم وتطوير أجيال الغد، من دون أن يسمح لبضعة أيام جيدة أو سيئة بأن تعيد تشكيل نموذج الإنتاج. الهدف ليس التغيير المستمر؛ الهدف هو التحسن المنضبط.</p></div></section>

    <section class="methodology-section"><span class="methodology-index">05 / ما وراء الموقع</span><div class="methodology-copy"><h2>ما تراه على الموقع هو سطح البحث، وليس غرفة المحرك.</h2><p>ما يُنشر للعامة مقصود أن يكون محدوداً وواضحاً: الترتيب اليومي، واتجاه النموذج، وتغير الترتيب، والآفاق الأربعة، وذاكرة النموذج العامة، وإفصاحات الأدلة، وسجل عام قابل للقراءة آلياً. هذه الطبقة تكفي لفهم ما يقوله النموذج والتحقق مما نُشر.</p><p>أما النظام البحثي خلف هذه الطبقة فأوسع بكثير. فهو يحتفظ بذاكرة سوق مستمرة، ويتحقق من المشاهدات، ويحفظ التوقعات، ويقيّم النتائج الناضجة، ويراقب جودة المصدر والانحراف والثقة، ويدعم أبحاث النماذج المتحدية تحت الحوكمة. هذه القدرات موجودة لجعل الإشارة العامة أكثر انضباطاً، لا لتحويل الموقع إلى مستودع تقني للمحرك.</p><div class="public-private"><article><span>السطح العام</span><h3>ما يحتاجه المستثمر لاستخدام /Alpha والتحقق منه.</h3><p>الترتيب · اتجاه النموذج · تغير الترتيب · 1D / 3D / 5D / 10D · السجل · الأدلة · JSON العام.</p></article><article><span>النظام البحثي الخاص</span><h3>ما يحافظ على انضباط الإشارة مع الزمن.</h3><p>ذاكرة مستمرة · جودة المشاهدات · تقييم النتائج الفعلية · مراقبة الانحراف والثقة · أبحاث النماذج المتحدية · سجل التدقيق.</p></article></div><div class="methodology-actions"><a href="${rel('/data/latest.json')}">تحقق من السجل العام</a><a href="${rel('/institutional/')}">البحث المؤسسي</a></div></div></section>

    <section class="methodology-section"><span class="methodology-index">06 / أجندة البحث</span><div class="methodology-copy"><h2>عمق أكبر. أدلة أكثر. بلا تعقيد لمجرد الاستعراض.</h2><p>أجندة البحث المقبلة تركز على جعل الترتيب أكثر متانة وفائدة من دون إضعاف الانضباط الذي يمنحه قيمته. أي قدرة جديدة يجب أن تخدم سؤال /Alpha الأصلي: كيف نحدد الفرص النسبية داخل السوق المصري بصورة أفضل؟</p><div class="agenda-grid"><article class="agenda-card"><span>01</span><strong>الصلابة عبر أنظمة السوق</strong><p>دراسة بقاء أجيال النموذج مفيدة مع تغير ظروف السوق والعلاقات داخله.</p></article><article class="agenda-card"><span>02</span><strong>عمق الأدلة</strong><p>توسيع أدلة النتائج الحية الناضجة والمعايرة والمساءلة طويلة الأجل للنموذج.</p></article><article class="agenda-card"><span>03</span><strong>ذكاء الآفاق المتعددة</strong><p>دراسة متى يحمل الاتفاق أو الاختلاف بين 1D و3D و5D و10D معلومة بحثية مفيدة.</p></article><article class="agenda-card"><span>04</span><strong>بنية السوق</strong><p>تعميق تمثيل النظام البحثي للعلاقات المتغيرة داخل عالم أسهم EGX.</p></article><article class="agenda-card"><span>05</span><strong>أجيال نموذجية محكومة</strong><p>تطوير نماذج متحدية تحت الانضباط نفسه: أدلة أولاً، ثم تقييم، ثم مراجعة بشرية.</p></article><article class="agenda-card"><span>06</span><strong>واجهات بحث مؤسسية</strong><p>توسيع توزيع البحث بصورة محكومة من دون كشف جوهر النموذج الخاص.</p></article></div></div></section>

    <section class="reference-block"><h2>المراجع والتحقق.</h2><p>المراجع الخارجية تضع الأفكار السابقة في سياقها العلمي والسوقي، ولا تصف تنفيذ EGX /Alpha الخاص. أما المراجع الداخلية فتمكّن أي زائر من التحقق من المخرجات العامة وتسلسلها الزمني.</p>${sharedReferenceGrid(true)}</section>
    <aside class="methodology-closing methodology-case-studies" aria-labelledby="methodology-case-studies-title-ar">
      <header class="case-study-head"><span class="case-study-kicker">توقعات EX-ANTE · نتائج سوق فعلية لاحقة</span><h2 id="methodology-case-studies-title-ar">دراسات حالة EGX /Alpha</h2><p class="case-study-intro">تبدأ كل دراسة بتوقعات محفوظة قبل معرفة النتيجة السوقية اللاحقة، ثم تتحقق من مسار التداول المحاكى باستخدام أسعار EGX وتوافر التداول الفعلي بعد نضج التوقع.</p></header>
      <div class="case-study-list">
        <details class="case-study-record"><summary><span class="case-study-number">01</span><strong>EGX /Alpha Rank 1 vs. Rank 1+: A Comparative 1D/3D Exit-Discipline Trading Simulation</strong><span class="case-study-toggle" aria-hidden="true"></span></summary><div class="case-study-panel"><p>اختبار ex-ante محكوم: التنفيذ وخروج 1D/3D متطابقان، والاختلاف فقط في اختيار السهم؛ <strong>أنهى #1+ المحاكاة عند +22.31% مقابل +20.80% لـ raw #1.</strong></p><a class="case-study-download" href="${rel('/assets/case-studies/EGX_Alpha_Case_Study_2.pdf')}" download>تنزيل دراسة الحالة · PDF <span aria-hidden="true">↓</span></a></div></details>
        <details class="case-study-record"><summary><span class="case-study-number">02</span><strong>EGX /Alpha Rank 1 vs. Rank 1+: Comparative Next-Session Whole-Share Trading Simulations</strong><span class="case-study-toggle" aria-hidden="true"></span></summary><div class="case-study-panel"><p>غيّر اختيار الإشارة ex-ante المحفوظ مسار التداول بالكامل: <strong>نما حساب #1+ من مليون جنيه إلى +56.74%، بينما أنهى raw #1 عند −7.37%</strong> بالآليات نفسها.</p><a class="case-study-download" href="${rel('/assets/case-studies/EGX_Alpha_Case_Study_1.pdf')}" download>تنزيل دراسة الحالة · PDF <span aria-hidden="true">↓</span></a></div></details>
        <details class="case-study-record"><summary><span class="case-study-number">03</span><strong>Positive-Filtered vs. Raw-Rank Five-Sleeve Portfolios</strong><span class="case-study-toggle" aria-hidden="true"></span></summary><div class="case-study-panel"><p>اختبار محفظة يراعي سعة التداول كشف نتيجة معاكسة للتوقع: خفّض الترشيح الإيجابي معدل الدوران، لكن <strong>raw Top-5 فاز بعائد +15.61% مقابل +12.30%.</strong></p><a class="case-study-download" href="${rel('/assets/case-studies/EGX_Alpha_Case_Study_3.pdf')}" download>تنزيل دراسة الحالة · PDF <span aria-hidden="true">↓</span></a></div></details>
      </div>
    </aside>
  </article>`;
}
